export const surpriseMePrompts = [
  'an armchair in the shape of an avocado',
  'a surrealist dream-like oil painting by Salvador Dalí of a cat playing checkers',
  'teddy bears shopping for groceries in Japan, ukiyo-e',
  'an oil painting by Matisse of a humanoid robot playing chess',
  'panda mad scientist mixing sparkling chemicals, digital art',
  "a macro 35mm photograph of two mice in Hawaii, they're each wearing tiny swimsuits and are carrying tiny surf boards, digital art",
  '3D render of a cute tropical fish in an aquarium on a dark blue background, digital art',
  'an astronaut lounging in a tropical resort in space, vaporwave',
  'an oil painting portrait of a capybara wearing medieval royal robes and an ornate crown on a dark background',
  'a stained glass window depicting a hamburger and french fries',
  'a pencil and watercolor drawing of a bright city in the future with flying cars',
  'a sunlit indoor lounge area with a pool with clear water and another pool with translucent pastel pink water, next to a big window, digital art',
  'a fortune-telling shiba inu reading your fate in a giant hamburger, digital art',
  '"a sea otter with a pearl earring" by Johannes Vermeer',
  'an oil pastel drawing of an annoyed cat in a spaceship',
  'a painting of a fox in the style of Starry Night',
  'a bowl of soup that looks like a monster, knitted out of wool',
  'A plush toy robot sitting against a yellow wall',
  'A synthwave style sunset above the reflecting water of the sea, digital art',
  'Two futuristic towers with a skybridge covered in lush foliage, digital art',
  'A 3D render of a rainbow colored hot air balloon flying above a reflective lake',
  'A comic book cover of a superhero wearing headphones',
  'A centered explosion of colorful powder on a black background',
  'A photo of a Samoyed dog with its tongue out hugging a white Siamese cat',
  'A photo of a white fur monster standing in a purple room',
  "A photo of Michelangelo's sculpture of David wearing headphones djing",
  'A Samurai riding a Horse on Mars, lomography.',
  'A modern, sleek Cadillac drives along the Gardiner expressway with downtown Toronto in the background, with a lens flare, 50mm photography',
  'A realistic photograph of a young woman with blue eyes and blonde hair',
  'A man standing in front of a stargate to another dimension',
  'Spongebob Squarepants in the Blair Witch Project',
  'A velociraptor working at a hotdog stand, lomography',
  'A man walking through the bustling streets of Kowloon at night, lit by many bright neon shop signs, 50mm lens',
  'A BBQ that is alive, in the style of a Pixar animated movie',
  'A futuristic cyborg dance club, neon lights',
  'The long-lost Star Wars 1990 Japanese Anime',
  'A hamburger in the shape of a Rubik’s cube, professional food photography',
  'A Synthwave Hedgehog, Blade Runner Cyberpunk',
  'An astronaut encountering an alien life form on a distant planet, photography',
  'A Dinosaur exploring Cape Town, photography',
  'A Man falling in Love with his Computer, digital art',
  'A photograph of a cyborg exploring Tokyo at night, lomography',
  'Dracula walking down the street of New York City in the 1920s, black and white photography',
  'Synthwave aeroplane',
  'A man wanders through the rainy streets of Tokyo, with bright neon signs, 50mm',
  'A Space Shuttle flying above Cape Town, digital art',
  "A golden elephant statue in a field of daisies, oil painting",
"A mermaid sitting on a giant shell, watercolor",
"A treehouse on a cliff overlooking the ocean, pencil sketch",
"A flying unicorn above a rainbow, digital art",
"A city skyline made of candy, pastel colors",
"A giant jellyfish floating in space, oil painting",
"A castle on a hill surrounded by fog, black and white",
"A giraffe playing the violin in a meadow, watercolor",
"A hot air balloon above a desert landscape, digital art",
"A garden maze made of mirrors, neon colors",
"A dragon sleeping on a mountain, pencil sketch",
"A whale swimming in a sea of stars, oil painting",
"A robot orchestra playing on a stage, pastel colors",
"A giant mushroom forest with fireflies, watercolor",
"A haunted house on a hill, black and white",
"A waterfall cascading down a crystal mountain, digital art",
"A group of penguins ice-skating on a frozen lake, pencil sketch",
"A field of sunflowers with a rainbow in the background, oil painting",
"A rocket blasting off from a snowy landscape, pastel colors",
"A giant seashell with a pearl inside, watercolor",
"A carnival with a Ferris wheel and cotton candy, digital art",
"A lighthouse on a rocky coastline, neon colors",
"A phoenix rising from the ashes, oil painting",
"A train passing through a tunnel of cherry blossoms, pencil sketch",
"A group of astronauts exploring an alien planet, pastel colors",
"A desert landscape with a cactus garden, watercolor",
"A medieval castle with a moat and drawbridge, digital art",
"A whale shark swimming in a coral reef, neon colors",
"A giant tree with a treehouse built in, oil painting",
"A futuristic city with flying cars, pencil sketch",
];
